files: ^src/
exclude: ^src/dev_area/

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-docstring-first
          - id: name-tests-test
          - id: check-added-large-files
    
    - repo: local
      hooks:
          - id: ruff
            name: ruff
            entry: ruff check
            language: system
            types: [python]
            args: [
                "--fix",
                #"--unfixable", "F401,F841",  # Unused imports and variables
                "--ignore", "E501,E741",      # Line length and ambiguous variable names
                "--select", "E,F,I,UP",       # Error, F-strings, Imports, Upgrade
                "--target-version", "py310"
            ]
          - id: ruff-format
            name: ruff format
            entry: ruff format
            language: system
            types: [python]